library(fgsea)

# make new object class to organize results from step 1
setClass(Class = "step1_fgsea_result_obj", slots=list(unfiltered="list", gmt_large_list="list", input_gsea_datasets="list"))


####################################################################################################
#################################### FUNCTIONS -- DO NOT MODIFY ####################################
####################################################################################################
# function name: calculate_enrichment()
# description:
# input:
# output:
calculate_enrichment <- function(gmt_file_input, output_prefix, cnmf_spectra_scores_file, seed){
  # read in the spectra scores file generated by cNMF
  cnmf_spectra_scores <- read.csv(cnmf_spectra_scores_file, row.names = 1, sep = "\t")
  cnmf_spectra_scores <- t(cnmf_spectra_scores)
  
  # stores all of your GEPs and spectra scores sorted in decreasing order (pos -> neg) as a large list object
  input_gsea_datasets = list() 
  for (gep in colnames(cnmf_spectra_scores)){
    all_sorted_scores = cnmf_spectra_scores[order(cnmf_spectra_scores[,gep], decreasing = T),]
    gep_specific_sorted_scores = all_sorted_scores[,gep]
    gsea_for_gep_scores = gep_specific_sorted_scores[!is.na(gep_specific_sorted_scores)]
    input_gsea_datasets[[gep]] = gsea_for_gep_scores
  }
  
  
  # read in gmt files of interest for pathway and gene sets of interest
  gmt = read.gmt(gmtfile = gmt_file_input)
  
  # data wrangle gmt file into a large list object
  transformed_gmt = gmt %>% group_by(term) %>% summarise(gene_list = str_c(sort(gene), collapse = ","), .groups = 'drop')
  transformed_gmt = as.data.frame(transformed_gmt)
  gmt_large_list = list()
  for (i in 1:nrow(transformed_gmt)){
    gmt_large_list[[as.character(transformed_gmt[i, "term"])]] = unlist(stringr::str_split(transformed_gmt[i,'gene_list'], pattern = ','))
  }
  
  set.seed(seed)
  unfiltered_fgsea_results = list()
  # run fgsea on all GEPs available in your data and save them as a large list object called unfiltered_fgsea_results
  for (i in names(input_gsea_datasets)){
    squash_list <- unlist(input_gsea_datasets[as.character(i)])
    names(squash_list) <- stringr::str_remove(names(squash_list), pattern = "^\\d\\.")
    unfiltered_fgsea_results[[as.character(i)]] <- fgsea(pathways = gmt_large_list, stats = squash_list, maxSize=500, minSize=15)
  }
  
  # save fgsea results for all GEPs so you don't need to re-run
  step1_enrichment_results = new(Class = "step1_fgsea_result_obj", unfiltered = unfiltered_fgsea_results, gmt_large_list = gmt_large_list, input_gsea_datasets = input_gsea_datasets)
  save(step1_enrichment_results, file = paste(output_prefix, "_unfiltered.Rdat", sep = ""))
  
  return(new(Class = "step1_fgsea_result_obj", unfiltered = unfiltered_fgsea_results, gmt_large_list = gmt_large_list, input_gsea_datasets = input_gsea_datasets))
}

# function name: filter_results()
# description:
# input:
# output:
filter_results <- function(unfiltered_fgsea_results, adjp_thresh, nes_thresh){
  filtered_fgsea_results = list()
  if (nes_thresh == 'positive'){
    for (i in names(unfiltered_fgsea_results)){
      curr_gep_res = unfiltered_fgsea_results[[i]]
      filtered_fgsea_results[[i]] = curr_gep_res[which(curr_gep_res[,"padj"] < adjp_thresh & curr_gep_res[,"NES"] > 0),]
    }
    save(filtered_fgsea_results, file = paste(output_prefix, "_filtered_padj_", adjp_thresh, "_nes_", nes_thresh, ".Rdat", sep = ""))
    return(filtered_fgsea_results)
  }else if (nes_thresh == 'negative'){
    for (i in names(unfiltered_fgsea_results)){
      curr_gep_res = unfiltered_fgsea_results[[i]]
      filtered_fgsea_results[[i]] = curr_gep_res[which(curr_gep_res[,"padj"] < adjp_thresh & curr_gep_res[,"NES"] < 0),]
    }
    save(filtered_fgsea_results, file = paste(output_prefix, "_filtered_padj_", adjp_thresh, "_nes_", nes_thresh, ".Rdat", sep = ""))
    return(filtered_fgsea_results)
  }else if (nes_thresh == 'both'){
    for (i in names(unfiltered_fgsea_results)){
      curr_gep_res = unfiltered_fgsea_results[[i]]
      filtered_fgsea_results[[i]] = curr_gep_res[which(curr_gep_res[,"padj"] < adjp_thresh),]
    }
    save(filtered_fgsea_results, file = paste(output_prefix, "_filtered_padj_", adjp_thresh, "_nes_", nes_thresh, ".Rdat", sep = ""))
    return(filtered_fgsea_results)
  }else {
    print(paste("nes_threshold of: ", nes_thresh, " is invalid.  Please select one of the following options: positive, negative, both"))
  }
}

# function name: table_summary_plot()
# description:
# input:
# output:
table_summary_plot <- function(filtered_results, gmt_large_list, input_gsea_datasets, gep_id, pathway_names = NULL){
  sorted_by_nes = filtered_results[[gep_id]][order(filtered_results[[gep_id]][,"NES"], decreasing = T),]
  if (is.null(pathway_names)){
    num_to_plot = min(nrow(sorted_by_nes), 10)
    pathway_list = sorted_by_nes[1:num_to_plot]$pathway
    plotGseaTable(gmt_large_list[pathway_list], input_gsea_datasets[[gep_id]], filtered_results[[gep_id]], gseaParam=0.5)
  }else{
    plotGseaTable(gmt_large_list[pathway_names], input_gsea_datasets[[gep_id]], filtered_results[[gep_id]], gseaParam=0.5)
  }
}

# function name: traditional_gsea_plot()
# description:
# input:
# output:
traditional_gsea_plot <- function(gmt_large_list, input_gsea_datasets, gep_id, pathway_name){
  plotEnrichment(gmt_large_list[[pathway_name]], input_gsea_datasets[[gep_id]]) + 
    ggtitle(pathway_name) +
    theme(plot.title = element_text(hjust = 0.5))
  
  # plotEnrichment(gmt_large_list[['HALLMARK_MYC_TARGETS_V1']], input_gsea_datasets[["2"]]) + 
  #   theme_classic() +
  #   scale_x_continuous('Rank', breaks = seq(0, 32000, 5000)) +
  #   scale_y_continuous('Enrichment score (ES)') +
  #   geom_line(col = 'blue', linewidth = 1, linetype = "dashed")+
  #   ggtitle("HALLMARK_MYC_TARGETS_V1") +
  #   theme(plot.title = element_text(hjust = 0.5))
}

# function name: traditional_gsea_plot()
# description:
# input:
# output:
get_leading_edge <- function(filtered_results, gep_id, pathway_name){
  filtered_results[[gep_id]][which(filtered_results[[gep_id]][,"pathway"] == pathway_name)]$leadingEdge
}

####################################################################################################
######################################### END OF FUNCTIONS #########################################
####################################################################################################
